TESTS WITH ERRORS 
test03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 73, in test03
    actual = self.KB.kb_explain(fact4)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 180, in kb_explain
    return(self.kb_explain_helper(fact_or_rule, count))
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 139, in kb_explain_helper
    rep = 'fact: ' + '(' + fact.statement.predicate + ' ' + str(fact.statement.terms[0]) + ' ' + str(fact.statement.terms[1]) + ')'
IndexError: list index out of range

-------------------------------
TESTS FAILED  
-------------------------------
TESTS SKIPPED 
-------------------------------
